// sub-projects/vue-demo/src/App.vue
<template>
  <div id="app">
    <img alt="Vue logo" src="./assets/logo.png" />
    <HelloWorld msg="Vue Sub App" />
  </div>
</template>

<script>
import HelloWorld from "./components/HelloWorld.vue";

export default {
  name: "App",
  components: {
    HelloWorld
  }
};
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>

// standard-projects/svelte-demo/src/App.svelte
<script>
	export let name;
	let src = "assets/logo.png";
</script>

<main>
	<img src={src} alt="logo">
	<h1>Svelte {name}</h1>
</main>

<style>
	main {
		text-align: center;
		background-color: antiquewhite;
		display: flex;
		align-items: center;
		justify-content: center
	}

	h1 {
		color: #ff3e00;
		/* text-transform: uppercase; */
		font-size: 4em;
		font-weight: 100;
	}

</style>
